Next-Room/nextroomfe

app/style/ThemeMUI.json
stories/Button.component.tsx
stories/Button.stories.tsx
stories/Dialog.component.tsx
stories/Dialog.stories.tsx
stories/Drawer.component.tsx
stories/Drawer.stories.tsx
stories/Snackbar.stories.tsx
stories/TextField.component.tsx
stories/TextField.stories.tsx

- 스토리북 QA 수정사항
- 텍스트필드 및 버튼 컴포넌트 내용 추가했습니다
<br><br>

feat: story book

---

app/admin/page.tsx
app/home/Home.tsx
app/page.tsx

- 랜딩 페이지를 `/`으로
- login 페이지를 `/admin`으로 변경했습니다.
- Admin 메인 페이지는 이전과 동일하게 `/main` URL을 사용했습니다.
<br><br>

chore: change URL

---

app/components/landing/mobile/Component1Mobile.tsx
app/components/landing/mobile/Component9Mobile.tsx
app/components/landing/mobile/MobileBtn.tsx
app/components/landing/pc/Component1.tsx
app/components/landing/pc/Component9.tsx
app/components/landing/pc/PcBtn.tsx
app/landing/LandingView.tsx

- 랜딩 페이지 일부 문구 수정했습니다.
<br><br>
- 랜딩 페이지 8번 항목 코멘트 처리했어요.
<br><br>

feature: modify message on landing page

---

app/consts/components/trial.ts

- 텍스트 문구 수정 (무료체험 미반영된 
<br><br>

chore: change trial message

---

app/admin/page.tsx
app/components/MakeThemePage/MakeThemePage.tsx
app/components/RequireAuth/RequireAuth.tsx
app/components/common/DeleteDialog/DeleteDialog.tsx
app/components/common/Drawer/Drawer.tsx
app/components/common/EmptyHome/EmptyHomeView.tsx
app/consts/components/home.ts
app/home/Home.tsx
app/home/HomeView.tsx
app/login/Login.tsx
app/login/page.tsx

- admin 무한로딩
- title명 변경
- 삭제 다이얼로그 오류 수정
<br><br>
- admin 페이지에 home 컴포넌트를 연결했어요 
<br><br>
- 급하게 수정하느라 다시 한번 확인이 필요합니닷 ㅠㅡㅠ
<br><br>

Fix: url layout

---

app/components/common/EmptyHome/EmptyHomeView.styled.ts
app/components/common/EmptyHome/EmptyHomeView.tsx
app/consts/components/home.ts

- 버튼 스타일과 글자 스타일 변경했어요
<br><br>

Style: modify home style

---

app/components/RequireAuth/RequireAuth.tsx

- 랜딩페이지에서 새로고침시 이동하는 현상 수정
- 모바일 막기 추가(어드민/로그인 페이지)
- develop에 잘못 푸쉬해서 이것도 같이 봐주세요! https://github.com/Next-Room/nextRoomFE/commit/7ce4a2cafd9e4690667d9198370fa65101177aa1
<br><br>
<br><br>

Fix: not blockMobile landing page

---

app/components/HintItem/HintItemView.styled.ts
app/components/HintList/HintList.styled.ts

- 힌트리스트 가변적인 ui를 고정했어요
<br><br>

style:fix width  hintList

---

app/apis/ChannelTalk.tsx
app/apis/Clarity.tsx
app/layout.tsx

- 채널톡, MS Clarity 삽입 스크립트를 추가했습니다.
<br><br>

feature: add channel talk, clarity script

---

app/signup/CodeInput.tsx
app/signup/NewTextField.component.tsx
app/signup/Password.tsx
app/signup/PasswordView.tsx
app/signup/SignUp.tsx
app/signup/SignUpSuccess.tsx
app/signup/SignUpView.styled.ts
app/signup/SignUpView.tsx

- 비밀번호 입력 시 엔터로 다음 인풋에 포커스 
- 인증번호 숫자형식으로 변경
- 회원가입 완료시 url연결
- 이메일 입력시 에러 메세지 추가
<br><br>
-  qa
<br><br>

Fix: signup

---

app/components/MakeThemePage/MakeThemePage.tsx
app/components/RequireAuth/RequireAuth.tsx
app/components/common/DeleteDialog/DeleteDialog.tsx
app/components/common/Drawer/Drawer.tsx

- theme 이동하는 주소 기준을 이름에서 테마 아이디로 변경했습니다.\
<br><br>
- title을 themeId로 바꿨습니다.
<br><br>

feat: applied router condition

---

app/components/landing/mobile/Component1Mobile.tsx
app/components/landing/mobile/Component9Mobile.tsx
app/components/landing/mobile/MobileBtn.tsx
app/components/landing/pc/Component1.tsx
app/components/landing/pc/Component9.tsx
app/components/landing/pc/PcBtn.tsx
app/landing/Landing.tsx
app/landing/LandingView.tsx
app/login/Login.tsx
app/login/LoginView.tsx
app/signup/SignUp.tsx
app/signup/SignUpView.tsx
app/signup/layout.tsx
app/utils/cookie.ts

- 뒤로가기시 쿠키 사용
- 로컬에선 작동하는데 배포시 작동되지 않는 문제 쿠키를 사용함
<br><br>
- [ x] docs 수정이 필요한지 검토해보았고, 필요한 경우 docs를 수정했습니다.

뒤로가기시 쿠키 사용

---

app/components/landing/mobile/Component1Mobile.tsx
app/components/landing/mobile/Component9Mobile.tsx
app/components/landing/mobile/MobileBtn.tsx
app/components/landing/pc/Component1.tsx
app/components/landing/pc/Component9.tsx
app/components/landing/pc/PcBtn.tsx
app/landing/Landing.tsx
app/login/LoginView.styled.ts
app/signup/EmailAuth.tsx
app/signup/EmailAuthView.tsx
app/signup/Password.tsx
app/signup/PasswordView.tsx
app/signup/SignUp.tsx
app/signup/SignUpSuccess.styled.ts
app/signup/SignUpSuccess.tsx
app/signup/SignUpView.styled.ts
app/signup/SignUpView.tsx
app/signup/StoreInfo.tsx
app/signup/StoreInfoView.tsx

- qa 스타일 수정
- 이벤트 url 수정 밑 버튼 ga추가
<br><br>
<br><br>
<br><br>

Feat/signup Qa

---

app/apis/Analytics.tsx
app/apis/ChannelTalk.tsx
app/apis/Clarity.tsx
app/consts/env.ts

- Dev 모드일 때는 외부 스크립트가 실행되지 않도록 수정했습니다.
<br><br>
- isDevMode 상태 추가
<br><br>

fix: 데브 모드일 때 스크립트 제거

---

app/login/LoginView.tsx

- 로그인 화면에 유저 가이드 링크를 추가했습니다.
- 일단 디자인 없어서 임시로 이렇게 넣어놓고 디자인 나오면 다시 수정할게!

chore: added user guide link

---

app/components/common/Drawer/Drawer.tsx
app/components/common/Drawer/DrawerView.styled.ts
app/login/LoginView.tsx

- 로그인 페이지 말고 사이드바로 유저 가이드 링크 이동

chore: moved user guide link

---

app/components/MakeThemePage/MakeThemePageView.styled.ts
app/components/common/Drawer/Drawer.tsx
app/components/common/Drawer/DrawerView.styled.ts
app/signup/NewTextField.component.tsx
app/signup/SignUpSuccess.styled.ts
app/signup/SignUpView.styled.ts
app/signup/StoreInfo.tsx

- QA반영
- [링크](https://www.notion.so/8657955e2c974c529aa63f3dce4334ea?v=9c5f082a4f9d4fbe8a9961d1a74387b8)
- 테마 추가 페이지 하단 버튼 튀어나오는거 임시로 수정함

style: QA반영

---

app/signup/SignUpSuccess.tsx

- 회원가입 완료 화면 버튼 webView 분기 처리가 제대로 안되어서 수정
- webView 일 경우 모바일에 postMessage 를 보내서 닫기 기능을 구현해야하는데 추후 명범이랑 해결 예정,,! //TODO
<br><br>

feat: modify isWebView btn

---

app/apis/ChannelTalk.tsx

feat: 회원가입 페이지 채널톡 예외처리

---

.vscode/settings.json
app/components/landing/mobile/Component1Mobile.tsx
app/components/landing/mobile/Component2Mobile.tsx
app/components/landing/mobile/Component8Mobile.tsx
app/components/landing/mobile/Component9Mobile.tsx
app/components/landing/mobile/MobileBtn.tsx
app/components/landing/mobile/Phone.tsx
app/components/landing/mobile/Phone2.tsx
app/components/landing/mobile/Phone3.tsx
app/components/landing/mobile/Phone4.tsx
app/components/landing/pc/Component1.tsx
app/components/landing/pc/Component2.tsx
app/components/landing/pc/Component8.tsx
app/components/landing/pc/Component9.tsx
app/components/landing/pc/PcBtn.tsx
app/components/landing/pc/Phone.tsx
app/components/landing/pc/Phone2.tsx
app/components/landing/pc/Phone3.tsx
app/components/landing/pc/Phone4.tsx
app/hooks/useAnalytics.ts
app/signup/EmailAuth.tsx
app/signup/Password.tsx
app/signup/SignUp.tsx
app/signup/SignUpSuccess.tsx
app/signup/StoreInfo.tsx
app/trial/Trial.tsx
app/trial/TrialView.tsx

- dev 서버에서 analytic 요청되지 않도록 수정!
<br><br>
- `useAnalytics` 훅 추가 
<br><br>

fix: prevent request gtag when mode is dev

---

app/hooks/useClickOutside.ts
app/signup/NewTextField.component.tsx
app/signup/Password.tsx
app/signup/SignUp.tsx
app/signup/StoreInfo.tsx
app/signup/style.css

추후 css 파일은 수정예정
- 텍스트 필드 수정완료
- 앞으로 사용할 텍스트 필드
<br><br>
- useOutsideClick 훅
<br><br>
- css 파일 스타일드 컴포넌트로 추후 변경,, 시간관계상
- 
<br><br>

feat: 텍스트필드 수정완

---

app/components/HintList/HintList.styled.ts
app/home/HomeView.styled.ts
app/signup/SignUpView.styled.ts

- 가입 버튼 컬러 수정
- 힌트 추가하기 float 버튼 크기 고정
- 메인 레이아웃 일정 크기 이하로 줄어들 경우 x 스크롤 활성화
<br><br>

디자인 QA 몇 가지 반영

---

.storybook/preview.tsx
app/home/HomeView.styled.ts
stories/Color.component.tsx
stories/Color.stories.tsx
stories/Font.component.tsx
stories/Font.stories.tsx

feat: 폰트, 컬러 디자인 시스템 추가

---

app/style/theme.tsx

feat: theme 추가

---

app/admin-new/Admin.tsx
app/admin-new/AdminView.tsx
app/admin-new/admin.css
app/admin-new/admin.sass
app/style/_variables.sass
stories/NewButton.component.tsx
stories/NewButton.stories.tsx
stories/_button.css

- qa 전 색상 안바뀐 게 있어서 머지하겠습니당! 
<br><br>
<br><br>
<br><br>

style: 색상 변경

---

app/admin-new/admin.css
app/admin-new/admin.sass

style: 1차 어드민 QA 수정사항

---

app/admin-new/(components)/ContentArea.tsx
app/admin-new/(components)/Sidebar.tsx
app/admin-new/(consts)/sidebar.ts
app/admin-new/AdminView.tsx
app/admin-new/admin.css
app/admin-new/admin.sass

- 컴포넌트 분리 및 디자인 1차 qa 반영
<br><br>

feat: 디자인 qa 및 컴포넌트 분리 

---

app/admin-new/AdminView.tsx
app/admin-new/admin.css
app/admin-new/admin.sass

style: 디자인 해상도 qa

---

package.json
pnpm-lock.yaml
tsconfig.json

- pnpm run build 에서 types 못 찾는 에러
<br><br>
- [ x] 브랜치 전략에 맞는 브랜치에 PR을 올리고 있습니다. (master/main이 아닙니다.)
- [ x] 커밋 메세지를 컨벤션에 맞추었습니다.
- [ x] 변경 후 코드는 컴파일러/브라우저 warning/error 가 발생시키지 않습니다.
- [ x] 변경 후 코드는 기존의 테스트를 통과합니다.
- [ x] 테스트 추가가 필요한지 검토해보았고, 필요한 경우 테스트를 추가했습니다.
- [ x] docs 수정이 필요한지 검토해보았고, 필요한 경우 docs를 수정했습니다.

fix: pnpm run build 에러

---

package.json
pnpm-lock.yaml
tsconfig.json

Reverts Next-Room/nextRoomFE#61

Revert "fix: pnpm run build 에러"

---

app/(shared)/(ThemeTextField)/Container.tsx
app/(shared)/(ThemeTextField)/textField.modules.sass
app/(shared)/(ThemeTextField)/useTextField.tsx
app/admin-new/(components)/CreateTheme/Container.tsx
app/admin-new/(components)/CreateTheme/CreateThemeAddButton.tsx
app/admin-new/(components)/CreateTheme/CreateThemeBody.tsx
app/admin-new/(components)/CreateTheme/createTheme.ts
app/admin-new/(components)/Sidebar.tsx
app/admin-new/(components)/ThemeInfo/Container.tsx
app/admin-new/(consts)/sidebar.ts
app/admin-new/(style)/admin.modules.sass
app/admin-new/Admin.tsx
app/components/RequireAuth/RequireAuth.tsx
app/components/atoms/createTheme.atom.ts
app/components/common/Dialog-new/Dialog.tsx
app/components/common/Dialog-new/dialog.css
app/mutations/putTheme.ts

feat: 2차 QA

---

.eslintrc.json
app/(shared)/(ThemeTextField)/TextFieldType.ts
app/(shared)/(ThemeTextField)/useTextField.tsx
app/admin-new/(components)/ThemeInfo/Container.tsx
app/admin-new/(components)/ThemeInfo/ThemeDrawer.tsx
app/admin-new/(components)/ThemeInfo/ThemeInfoBody.tsx
app/admin-new/(components)/ThemeInfo/ThemeInfoHint.tsx
app/components/atoms/createHint.atom.ts
app/components/atoms/selectedHint.atom.ts
app/components/common/Hint-Dialog-new/Dialog.tsx
app/components/common/Hint-Dialog-new/DialogBody.tsx
app/components/common/Hint-Dialog-new/ModalPortal.tsx
app/components/common/Hint-Dialog-new/dialog.css
app/components/common/Hint-Dialog-new/dialog.sass
app/mutations/postHint.ts
app/queries/getHintList.ts
app/queries/getPreSignedUrl.ts
app/types/index.ts
next.config.js

feat: api연결

---

app/admin-new/(components)/CreateTheme/Container.tsx
app/admin-new/(components)/Sidebar.tsx
app/hooks/useCheckSignIn.ts
app/login/LoginView.tsx
app/mutations/postTheme.ts
app/queries/getSubscriptionPlan.ts
app/utils/localStorage.ts

- 구독 상태를 쿠키에 넣고
- 사이드바에서 구독 상태가 free이면 배너가 뜨도록
<br><br>
<br><br>
<br><br>

feat: 구독 상태 추가

---

app/admin-new/(style)/admin.modules.sass
app/admin-new/(style)/themeInfo.modules.sass
package-lock.json

fix: css 코드 누락 추가

---

app/admin/(components)/Sidebar.tsx
app/admin/(components)/ThemeDrawer/hooks/useImages.ts
app/admin/(style)/admin.modules.sass
app/components/common/Hint-Dialog-new/Dialog.tsx
app/queries/getPreSignedUrl.ts
app/queries/getSubscriptionPlan.ts
app/utils/localStorage.ts

- 이 브랜치 -> hint-qa4로 합쳐서 디벨롭에 반영
<br><br>
<br><br>
<br><br>

feat: 힌트 qa 4차

---

.eslintrc.json
app/(shared)/(ThemeTextArea)/Container.tsx
app/(shared)/(ThemeTextArea)/TextAreaType.ts
app/(shared)/(ThemeTextArea)/textArea.modules.sass
app/(shared)/(ThemeTextArea)/useTextArea.tsx
app/admin/(components)/Sidebar.tsx
app/admin/(components)/ThemeDrawer/Container.tsx
app/admin/(components)/ThemeDrawer/ThemeDrawerAnswer.tsx
app/admin/(components)/ThemeDrawer/ThemeDrawerHint.tsx
app/admin/(components)/ThemeDrawer/consts/themeDrawerProps.ts
app/admin/(components)/ThemeDrawer/hooks/useImages.ts
app/admin/(components)/ThemeInfo/ThemeInfoHint.tsx
app/admin/(style)/admin.modules.sass
app/admin/(style)/themeInfo.modules.sass
app/components/common/Hint-Dialog-new/Dialog.tsx
app/queries/getPreSignedUrl.ts
app/queries/getSubscriptionPlan.ts
app/style/_button.sass
app/utils/localStorage.ts

- 스레드의 1,2,3,4,6
<br><br>
- [슬랙 링크](https://slack-jor1187.slack.com/archives/C05FM0RH4VC/p1732453297628769)
<br><br>

Feat: hint qa 4차 수정사항

---

app/signup/SignUpSuccess.styled.ts
app/signup/SignUpView.styled.ts

fix: 회원가입 버튼 disabled 미적용 해결

---

app/lib/reactQueryProvider.tsx

feat: 엑세스 토큰 없을 시 로그아웃 추가

---

app/signup/page.tsx

fix: signup 무한로딩 수정

---

app/(shared)/auth/storageUtil.ts
app/landing/components/mobile/Component1Mobile.tsx
app/landing/components/mobile/Component9Mobile.tsx
app/landing/components/mobile/MobileBtn.tsx
app/landing/components/pc/Component1.tsx
app/landing/components/pc/Component9.tsx
app/landing/components/pc/PcBtn.tsx
app/signup/hooks/useSignUpWithGoogle.ts

Feat/google UI

---

app/signup/components/HeaderLayout.tsx

fix: 빌드 에러 수정

---

app/signup/components/HeaderLayout.tsx

Reverts Next-Room/nextroomfe#111

Revert "fix: 빌드 에러 수정"

---

app/signup/components/HeaderLayout.tsx

Reverts Next-Room/nextroomfe#110

Revert "fix: Android에서 X버튼 노출하지 않게 수정"

---

app/(shared)/auth/hooks/useAuth.ts
app/landing/components/mobile/Component1Mobile.tsx
app/landing/components/pc/Component1.tsx

feat: video 적용, google redirect uri 환경변수화

---

app/(shared)/auth/hooks/useAuth.ts

chore: add console.warn

---

app/(shared)/auth/hooks/useAuth.ts
app/landing/components/mobile/Component1Mobile.tsx
app/landing/components/pc/Component1.tsx

Reverts Next-Room/nextroomfe#116

Revert "Landing Video"

---

app/(shared)/lib/reactQueryProvider.tsx
app/admin/apis/theme/getThemeList.ts
app/signup/apis/getGoogleCallback.ts
app/signup/apis/putSignUpWithGoogle.ts
package.json
pnpm-lock.yaml

- /api/v1/auth/login/google/callback 호출할 때
기존에 구글 로그인 시도 시 액세스 토큰 받은게 로컬스토리지에 존재 -> API 보낼 때 Auth 헤더에 함께 전송됨
-> 액세스 토큰 + 액세스 토큰 만료 시간 둘 다 있어야 보내는 방식으로 수정
- 가입 중 액세스 토큰 만료됐을 때 가입시도하면 에러 처리 안되어 페이지 멈춰있는 이슈 수정

구글 로그인 시 간헐적 발생 에러 픽스

---

app/landing/styles/snap.modules.sass

feat: 모바일 로고 노출 레이아웃 변경
